[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "prague"
optimizer = true
optimizer_runs = 200
via_ir = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
