[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "prague"
optimizer = true
optimizer_runs = 200
via_ir = true

# Gas配置 - 模拟真实网络环境
gas_limit = 30000000          # 30M gas limit (类似主网区块gas limit)
gas_price = 20000000000       # 20 gwei (典型的gas price)
block_base_fee_per_gas = 7    # 7 wei base fee

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
